# Generated by Django 2.2.18 on 2021-02-20 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_photo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
    ]
