# Generated by Django 2.2.18 on 2021-02-20 21:30

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210220_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('videoURL', embed_video.fields.EmbedVideoField()),
                ('category', models.CharField(max_length=50)),
                ('datePosted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
