# Generated by Django 2.2.18 on 2021-02-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_dronedescription_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='homePageBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
