# Generated by Django 2.2.18 on 2021-02-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_homepagebackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocollection',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
