# Generated by Django 2.2.18 on 2021-02-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210220_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
