# Generated by Django 2.2.18 on 2021-02-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210220_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photocollection',
            name='photos',
        ),
    ]
